### PR TITLE
Feature/filters for carra

### PR DESCRIPTION
**Pull request by tnipen**
Adds new filters needed for creating CARRA datasets:

- conversion from wz to w
- conversion from orog to z
- a filter to sum up a set of variables (needed to sum 4 components that make up total column integrated water, but is generic enough to sum any set of variables)

----
📚 Documentation preview 📚: https://anemoi-datasets--149.org.readthedocs.build/en/149/

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-datasets?pullRequest=149) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-datasets?pullRequest=149) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-datasets?pullRequest=149) it.</sub>

**Review by b8raoult — APPROVED** [review]

**Comment by b8raoult** [comment]
Your PR is still in draft mode

**Comment by tnipen** [comment]
Yes my intention was to open a draft PR. Shall I update the docs with the new filters?

**Comment by mchantry** [comment]
Really nice contribution and documentation. Feel free to remove the draft status if you are happy.

**Comment by mchantry** [comment]
The "code-quality" test is unhappy with your line-length in the documentation sorry.

**Comment by tnipen** [comment]
Thanks, I've fixed the issue. This is ready to be reviewed. My main hesitation is the choice of filter names: `wz_to_w` and `orog_to_z`. Happy to use something different if you prefer.

**Review by mchantry — APPROVED** [review]
Great work, thanks.

**Pull request merged**
